#!/data/data/com.termux/files/usr/bin/bash
# Created by Hax4us
clear
#colors
green='\033[1;32m'
red='\033[1;31m'
yellow='\033[1;33m'
reset='\033[0m'
echo
echo -e "$green Please wait ..."
echo
echo -e "$yellow Dependencies Installing ..."
echo
echo -e "$red installing  tools (also depend on your net speed)"
apt update -y && apt upgrade -y
apt install git python python3 php -y

	echo -e "$green installing social fish"
git clone https://github.com/UndeadSec/SocialFish
echo -e "$yellow cloned successfully "
echo
echo -e "$green Thanks guys"


clear
echo -e "$red Now you can exit and run the script $reset"
echo
