#!/data/data/com.termux/files/usr/bin/bash
# Created by varun
clear
#colors
green='\033[1;32m'
red='\033[1;31m'
yellow='\033[1;33m'
reset='\033[0m'
echo
echo -e "$green Script by varun"

echo
echo -e "$yellow Dependencies Installing ..."
echo
echo -e "$red installing tools"
apt update -y && apt upgrade -y
pkg install git python python3 php -y

	echo -e "$green installing social fish"
git clone https://github.com/UndeadSec/SocialFish  /data/data/com.termux/files/home/SocialFish
echo -e "$yellow cloned successfully " 

echo -e "$yellow installing dependencies"
pip install -r requirements.txt






echo
echo -e "$green Thanks guys"


clear
echo -e "$red Now just type cd .. cd SocialFish python3 socialfish.py $reset"
echo
